server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/back
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher